name: Migrate JSON to SQLite

on:
  push:
    branches:
      - master  # Изменено с main на master

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migration script
        run: |
          python migrate_json_to_sqlite.py

      - name: Commit and push database
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add /data/bot.db
          git commit -m "Update SQLite database after migration" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
